#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/gooroom
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3307/gooroom?characterEncoding=UTF-8&serverTimezone=UTC
##    username: hwan
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: 'leo!990706'
#    username: root

spring:
  datasource:
    username: root
    password: 'leo!990706'
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/mariadb?useSSL=false



  jpa:
    hibernate:
      ddl-auto: create-drop
      default_batch_fetch_size: 100
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB105Dialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    enabled: true
  profiles:
    include: oauth
    main:
      allow-bean-definition-overriding: true


jwt:
  secretKey: U2ltcGxlQm9hcmQtSnVuc2VvLVNwcmluZ0Jvb3QtVXNpbmdTcHJpbmdTZWN1cml0eS0yMDIzLTA0LTA5LXN1bmRheS13aXRoLU1hY2tib29rQWlyLUFpcnBvZHNwcm8taXBob25lMTRwcm8taXBhZGFyaXI0Cg==
  access:
    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization
  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh

logging:
  level:
    org.hibernate.SQL : debug
    org.hibernate.type: trace
    # org.apache.coyote.http11 : debug # http 로그 정보
server:
  address: 0.0.0.0
  port: 8080